env: "development"
grpc_server:
 address: "0.0.0.0"
 port: 6250
 timeout: "4s"
 idle_timeout: "60s"
database:
 firebird:
  connection_string: "SYSDBA:datalogic@server-psa/AgroStoreTest"
  max_open_connections: 10
  max_idle_connections: 5
  conn_max_lifetime: "5m"