env: "development"
grpc_server:
 address: "0.0.0.0"
 port: 6200
 timeout: "4s"
 idle_timeout: "60s"
database:
 mssql:
  connection_string: "sqlserver://sa:P@ssw0rd@server-sql4:1433?database=AgroReports"
  max_open_connections: 10
  max_idle_connections: 5
  conn_max_lifetime: "5m"